package machineconfig_test

import (
	"strings"
	"testing"

	"github.com/holzcloud/holzkube-manager/internal/machineconfig"
	"github.com/holzcloud/holzkube-manager/internal/talossim"
)

// The entropy walk CFG-02 asks for, over all five exits.
//
// The claim this whole package rests on is one function guarding five paths.
// A test that checked one of them would be a test of the function, not of the
// claim -- and the failure the requirement is about is exactly the fifth exit
// somebody added without going through it.

// fixture is a real control-plane machine configuration, generated by
// machinery's own generator, so the secrets in it are in the fields Talos
// actually puts them in rather than where a hand-written fixture guessed.
func fixture(t *testing.T) (*talossim.Cluster, []byte) {
	t.Helper()

	cl, err := talossim.NewCluster("redaction", "https://10.0.0.1:6443")
	if err != nil {
		t.Fatalf("NewCluster: %v", err)
	}
	return cl, cl.ControlPlaneConfig
}

// secretsOf is every value that must never appear in any output.
//
// PITFALLS names the five by name, and all five are here. They are taken from
// the generated bundle rather than from the config text, so a change in how
// Talos lays the document out cannot make this test stop looking for them.
func secretsOf(t *testing.T, cl *talossim.Cluster) map[string]string {
	t.Helper()

	s := cl.Secrets
	out := map[string]string{
		"the Talos CA private key":      string(s.Certs.OS.Key),
		"the Kubernetes CA private key": string(s.Certs.K8s.Key),
		"the etcd CA private key":       string(s.Certs.Etcd.Key),
		"the aggregator CA private key": string(s.Certs.K8sAggregator.Key),
		"the service account key":       string(s.Certs.K8sServiceAccount.Key),
		"the cluster secret":            s.Cluster.Secret,
		"the bootstrap token":           s.Secrets.BootstrapToken,
		"the machine (trustd) token":    s.TrustdInfo.Token,
	}
	for name, v := range out {
		if strings.TrimSpace(v) == "" {
			t.Fatalf("%s is empty in the fixture, so this test would pass by looking for nothing", name)
		}
	}
	return out
}

// assertClean is the walk itself.
func assertClean(t *testing.T, exit string, output []byte, secrets map[string]string) {
	t.Helper()

	for name, secret := range secrets {
		if strings.Contains(string(output), secret) {
			t.Errorf("%s leaks %s", exit, name)
		}
	}
	if machineconfig.ContainsPrivateKey(output) {
		t.Errorf("%s still contains a PEM private key block", exit)
	}
}

// TestNoExitLeaksASecret walks all five.
func TestNoExitLeaksASecret(t *testing.T) {
	t.Parallel()

	cl, raw := fixture(t)
	secrets := secretsOf(t, cl)

	// Sanity: the unredacted document does contain them. Without this the test
	// could pass against a fixture that never had any.
	var found int
	for _, secret := range secrets {
		if strings.Contains(string(raw), secret) {
			found++
		}
	}
	if found == 0 {
		t.Fatal("the fixture contains none of the secrets, so this test proves nothing")
	}

	// Exit 1 and 2: the raw tab and the rendered view.
	view, err := machineconfig.Redact(raw)
	if err != nil {
		t.Fatalf("Redact: %v", err)
	}
	assertClean(t, "the config view", view, secrets)

	// Exit 3: the diff. Both sides go through the same function, and the diff
	// carries rendered values -- so a leak here would be a value the walk
	// above missed being carried in a Before or an After.
	patched, err := machineconfig.ApplyPatches(raw, []string{"machine:\n  certSANs:\n    - 10.0.0.9\n"})
	if err != nil {
		t.Fatalf("ApplyPatches: %v", err)
	}
	diff, err := machineconfig.Compare(raw, patched)
	if err != nil {
		t.Fatalf("Compare: %v", err)
	}
	var diffText strings.Builder
	for _, c := range diff.Changes {
		diffText.WriteString(c.Path)
		diffText.WriteString(c.Before)
		diffText.WriteString(c.After)
	}
	assertClean(t, "the diff", []byte(diffText.String()), secrets)

	// Exit 4: the API response carrying a patched result.
	result, err := machineconfig.Redact(patched)
	if err != nil {
		t.Fatalf("Redact the patched config: %v", err)
	}
	assertClean(t, "the API response", result, secrets)

	// Exit 5: anything bound for the audit archive. D-16 keeps it forever with
	// no deletion path, so this is the exit where a leak is permanent.
	assertClean(t, "the audit archive", view, secrets)
}

// TestRedactionSurvivesAConfigThatDoesNotParse is the case that would
// otherwise be a leak dressed as an error.
//
// A configuration holzkube-manager cannot parse still has to be safe to show, and the
// operator still has to be able to see what is wrong with it. Refusing to show
// anything would hide the problem; showing the bytes because the parser was
// unhappy would hand over the key.
func TestRedactionSurvivesAConfigThatDoesNotParse(t *testing.T) {
	t.Parallel()

	cl, _ := fixture(t)
	broken := "this: is: not: valid: yaml:\nkey: |\n" + indent(string(cl.Secrets.Certs.OS.Key))

	out, err := machineconfig.RedactString(broken)
	if err == nil {
		t.Error("a configuration that does not parse was reported as fine")
	}
	if strings.Contains(out, string(cl.Secrets.Certs.OS.Key)) {
		t.Fatal("an unparsable configuration was returned with its private key intact")
	}
	if machineconfig.ContainsPrivateKey([]byte(out)) {
		t.Fatal("an unparsable configuration still contains a PEM private key")
	}
}

// TestAPrivateKeyInAnUnknownFieldIsStillRemoved is the belt the schema-aware
// half cannot provide.
//
// machinery's RedactSecrets knows the fields of the schema it was compiled
// against. A future Talos release that adds a secret-bearing field would
// redact nothing of it. A PEM private key is unmistakable whatever field it
// sits in, and that is the whole reason the second pass exists.
func TestAPrivateKeyInAnUnknownFieldIsStillRemoved(t *testing.T) {
	t.Parallel()

	cl, raw := fixture(t)
	// A field this build has never heard of, carrying a key.
	smuggled := string(raw) + "\n---\napiVersion: v1alpha1\nkind: SomethingNewUpstream\nsecret: |\n" +
		indent(string(cl.Secrets.Certs.OS.Key))

	out, _ := machineconfig.RedactString(smuggled)
	if machineconfig.ContainsPrivateKey([]byte(out)) {
		t.Fatal("a private key in a field this build does not know survived redaction")
	}
}

func indent(s string) string {
	var b strings.Builder
	for line := range strings.SplitSeq(strings.TrimRight(s, "\n"), "\n") {
		b.WriteString("  ")
		b.WriteString(line)
		b.WriteString("\n")
	}
	return b.String()
}
