import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { cleanup, render } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { page } from 'vitest/browser'
import { api, type Host, historySchema, hostSchema } from '@/api'
import { forget } from '@/hooks/useLiveSeries'
// The stylesheet is imported for its effect, not its exports: every class under
// measurement here is generated by Tailwind from this entry point. Without it
// nothing below has a layout worth measuring, and every element fits because
// nothing is styled -- a pass that measures nothing.
import '@/index.css'
import { HostView } from './host'

/**
 * The host page at 390 px, in a real browser (Phase 11, UI-SPEC backstops).
 *
 * jsdom performs no layout, so host.test.tsx can say that a class is present
 * but not that a 63-character hostname wraps instead of widening the page. This
 * file measures exactly two shapes the UI-SPEC left as backstops:
 *
 *   1. an amd64 desktop: container and hardening notices, k10temp twice, an
 *      nvme with limits, an nct6798 with two temperatures and five fans (one
 *      stopped), acpitz, three physical interfaces and twelve virtual ones with
 *      the disclosure open, two filesystem rows;
 *   2. long identifiers: hostname, model, OS, kernel, data-directory path and a
 *      filesystem device, each longer than a phone is wide.
 *
 * The page is rendered in a 390-px box inside a 390-px viewport, so the
 * breakpoints are the phone's. The rule measured is the one the phone suite
 * states for every route: no
 * element ends to the right of the page, except inside an element that scrolls
 * sideways on purpose (the ProcSubset=all code line does).
 */

vi.mock('@/routes/__root', () => ({
  authenticatedRoute: { addChildren: () => undefined },
}))

const PHONE_WIDTH = 390

const read = <T,>(value: T) => ({ readable: true as const, value })
const hidden = (code: string, message: string) => ({
  readable: false as const,
  reason: { code, message },
})

const HARDENING_STAT =
  "Hidden by the unit's ProcSubset=pid: /proc/stat is not visible to holzkube-manager. Set ProcSubset=all in the unit's [Service] section to show it."
const HARDENING_MEMINFO =
  "Hidden by the unit's ProcSubset=pid: /proc/meminfo is not visible to holzkube-manager. Set ProcSubset=all in the unit's [Service] section to show it."

const linkOf = (
  name: string,
  up: boolean,
  speed: number | null,
  rx: number | null,
  tx: number | null,
) => ({
  name,
  up,
  speed_mbit: speed,
  rx_bytes_per_sec: rx,
  tx_bytes_per_sec: tx,
})

const temp = (
  chip: string,
  kind: string,
  label: string,
  celsius: number,
  high: number | null,
  crit: number | null,
) => ({
  chip,
  kind,
  label,
  celsius,
  high_c: high,
  critical_c: crit,
})

const usage = {
  size_bytes: 1_000_204_886_016,
  used_bytes: 412_316_860_416,
  available_bytes: 536_870_912_000,
}

function shape({
  device = {},
  service = {},
  live = {},
  container = false,
}: {
  device?: Record<string, unknown>
  service?: Record<string, unknown>
  live?: Record<string, unknown>
  container?: boolean
}): Host {
  return hostSchema.parse({
    observed_at: '2026-09-28T10:00:03Z',
    container,
    device: {
      hostname: read('example-host'),
      model: read('Raspberry Pi 5 Model B Rev 1.0'),
      arch: read({ goarch: 'arm64', machine: 'aarch64' }),
      cores: read(4),
      os: read('Debian GNU/Linux 13 (trixie)'),
      kernel: read('6.12.47+rpt-rpi-2712'),
      uptime_seconds: read(26090),
      ...device,
    },
    service: {
      version: 'v0.1.0',
      started_at: '2026-09-28T08:00:00Z',
      uptime_seconds: 7203,
      data_dir: {
        path: '/var/lib/holzkube-manager',
        size: read({ bytes: 432013312, measured_at: '2026-09-28T09:59:40Z' }),
      },
      update: read({
        checked_at: '2026-09-28T09:00:12Z',
        installed: 'v0.1.0',
        latest: 'v0.1.1',
        outcome: 'available',
      }),
      ...service,
    },
    live: {
      rates_over_seconds: 3,
      cpu: {
        usage: hidden('hardening.proc-subset', HARDENING_STAT),
        per_core: hidden('hardening.proc-subset', HARDENING_STAT),
        load: read({ load1: 0.52, load5: 0.41, load15: 0.33, source: 'sysinfo' }),
      },
      memory: hidden('hardening.proc-subset', HARDENING_MEMINFO),
      filesystems: [
        {
          mount: '/',
          device: '/dev/mmcblk0p2',
          fstype: 'ext4',
          roles: ['root', 'data directory'],
          usage: read(usage),
        },
      ],
      sensors: read({
        temperatures: [temp('cpu_thermal', 'cpu', 'temp1', 64.4, null, null)],
        fans: [],
      }),
      network: read({ physical: [linkOf('eth0', true, 1000, 187900, 42100)], virtual: [] }),
      ...live,
    },
  })
}

/** A desktop amd64 host in a container, with every list a desktop board fills. */
function amd64(): Host {
  return shape({
    container: true,
    device: {
      hostname: read('workstation'),
      model: read('Micro-Star International Co., Ltd. MS-7C56'),
      arch: read({ goarch: 'amd64', machine: 'x86_64' }),
      cores: read(16),
      os: read('Ubuntu 24.04.3 LTS'),
      kernel: read('6.8.0-85-generic'),
    },
    live: {
      filesystems: [
        {
          mount: '/',
          device: '/dev/nvme0n1p2',
          fstype: 'ext4',
          roles: ['root'],
          usage: read(usage),
        },
        {
          mount: '/srv',
          device: '/dev/mapper/vg0-srv',
          fstype: 'xfs',
          roles: ['data directory'],
          usage: read({
            size_bytes: 4_000_787_030_016,
            used_bytes: 1_200_000_000_000,
            available_bytes: 2_800_787_030_016,
          }),
        },
      ],
      sensors: read({
        temperatures: [
          temp('k10temp', 'cpu', 'Tctl', 58.5, null, null),
          temp('k10temp', 'cpu', 'Tccd1', 51.25, null, null),
          temp('nvme', 'disk', 'Composite', 41.85, 81.85, 84.85),
          temp('nct6798', 'board', 'SYSTIN', 34, 80, null),
          temp('nct6798', 'board', 'AUXTIN0', 115, null, null),
          temp('acpitz', 'other', 'temp1', 16.8, null, 20.8),
        ],
        fans: [
          { chip: 'nct6798', label: 'fan1', rpm: 1024 },
          { chip: 'nct6798', label: 'fan2', rpm: 812 },
          { chip: 'nct6798', label: 'fan3', rpm: 0 },
          { chip: 'nct6798', label: 'fan4', rpm: 1530 },
          { chip: 'nct6798', label: 'fan5', rpm: 2210 },
        ],
      }),
      network: read({
        physical: [
          linkOf('enp5s0', true, 2500, 12_400_000, 3_100_000),
          linkOf('enp6s0', false, null, null, null),
          linkOf('wlp4s0', true, null, 0, 0),
        ],
        virtual: [
          linkOf('br-0a1b2c3d4e5f', true, 10000, 410, 260),
          linkOf('br-6f5e4d3c2b1a', true, 10000, 12, 0),
          linkOf('docker0', true, 10000, 320, 180),
          linkOf('lo', false, null, 1210, 1210),
          linkOf('tailscale0', true, null, 5200, 3100),
          linkOf('veth0a1b2c3', true, 10000, 410, 260),
          linkOf('veth1a2b3c4', true, 10000, 410, 260),
          linkOf('veth2a3b4c5', true, 10000, 0, 0),
          linkOf('veth3a4b5c6', true, 10000, 18, 9),
          linkOf('veth4a5b6c7', true, 10000, null, null),
          linkOf('virbr0', false, null, 0, 0),
          linkOf('wg0', true, null, 800, 950),
        ],
      }),
    },
  })
}

/** Every identifier the page shows, each longer than a phone is wide. */
function longIdentifiers(): Host {
  // 63 characters with no hyphen: the longest legal label, and one word with no
  // place the browser would break it of its own accord.
  const hostname = 'examplehost'.repeat(6).slice(0, 63)
  const model = 'Supermicro Super Server X13SAE-F-Ultra-Long-Board-Revision-2.00-ABCDEFGHIJ' // 70+
  const os = 'An-Operating-System-Name-With-No-Spaces-In-It-At-All-v123456' // 60
  const kernel = `6.12.47-${'k'.repeat(82)}` // 90
  const path = `/var/lib/holzkube-manager/${'d'.repeat(94)}` // 120
  const deviceName = `/dev/disk/by-id/nvme-Samsung_SSD_990_PRO_2TB_S7KHNJ0W${'x'.repeat(17)}` // 70
  expect(hostname).toHaveLength(63)
  expect(model.length).toBeGreaterThanOrEqual(70)
  expect(os).toHaveLength(60)
  expect(kernel).toHaveLength(90)
  expect(path).toHaveLength(120)
  expect(deviceName).toHaveLength(70)
  return shape({
    device: {
      hostname: read(hostname),
      model: read(model),
      os: read(os),
      kernel: read(kernel),
    },
    service: {
      data_dir: {
        path,
        size: read({ bytes: 432013312, measured_at: '2026-09-28T09:59:40Z' }),
      },
    },
    live: {
      filesystems: [
        {
          mount: '/',
          device: deviceName,
          fstype: 'ext4',
          roles: ['root', 'data directory'],
          usage: read(usage),
        },
      ],
    },
  })
}

function renderAtPhoneWidth(host: Host): HTMLElement {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  const { container } = render(
    <QueryClientProvider client={client}>
      <div data-testid="phone" style={{ width: `${PHONE_WIDTH}px` }}>
        <HostView host={host} stale={null} />
      </div>
    </QueryClientProvider>,
  )
  const phone = container.querySelector<HTMLElement>('[data-testid="phone"]')
  if (phone === null) throw new Error('the 390-px container did not render')
  // Every disclosure open: the virtual interfaces are part of what must fit.
  for (const d of phone.querySelectorAll('details')) d.open = true
  return phone
}

/** True when node sits inside an element (below root) that scrolls sideways by design. */
function scrollsSideways(node: Node, root: Element): boolean {
  for (let a = node.parentElement; a !== null && a !== root; a = a.parentElement) {
    const ox = getComputedStyle(a).overflowX
    if (ox === 'auto' || ox === 'scroll') return true
  }
  return false
}

/**
 * True inside an `sr-only` element: a 1-px box that clips its content, whose
 * text is laid out past it and never drawn. The sensors' "critical" label is one.
 */
function screenReaderOnly(el: Element, root: Element): boolean {
  for (let a: Element | null = el; a !== null && a !== root; a = a.parentElement) {
    const r = a.getBoundingClientRect()
    if (r.width <= 1 && r.height <= 1 && getComputedStyle(a).overflowX === 'hidden') return true
  }
  return false
}

function describeEl(el: Element): string {
  const text = (el.textContent ?? '').replace(/\s+/g, ' ').trim().slice(0, 80)
  return `<${el.tagName.toLowerCase()} class="${el.getAttribute('class') ?? ''}"> "${text}"`
}

/**
 * Every element and every run of text that ends right of the container, with
 * where it ends.
 *
 * Elements alone are not enough, and that was measured: a block that does not
 * wrap keeps its own box at the container's width while its text runs on past
 * it, so a notice set to `whitespace-nowrap` passed an element-only check. The
 * text is therefore measured line by line, through a Range over each text node.
 */
function overflowing(phone: HTMLElement): string[] {
  const edge = phone.getBoundingClientRect().right + 0.5
  const out: string[] = []
  for (const el of phone.querySelectorAll('*')) {
    const r = el.getBoundingClientRect()
    if (r.width === 0 && r.height === 0) continue
    if (r.right <= edge) continue
    if (scrollsSideways(el, phone)) continue
    out.push(`${describeEl(el)} ends at ${r.right.toFixed(1)} > ${edge.toFixed(1)}`)
  }
  const walker = document.createTreeWalker(phone, NodeFilter.SHOW_TEXT)
  const range = document.createRange()
  for (let n = walker.nextNode(); n !== null; n = walker.nextNode()) {
    const parent = n.parentElement
    if (parent === null || scrollsSideways(n, phone) || screenReaderOnly(parent, phone)) continue
    range.selectNodeContents(n)
    const right = Math.max(0, ...[...range.getClientRects()].map((r) => r.right))
    if (right <= edge) continue
    out.push(`text of ${describeEl(parent)} ends at ${right.toFixed(1)} > ${edge.toFixed(1)}`)
  }
  return out
}

// The viewport, not only the container, is 390 px wide: the cards switch their
// label column on at the md breakpoint, and a media query reads the viewport.
// A 390-px box inside the project's 1200-px viewport would measure the desktop
// grid squeezed into a phone's width -- a layout no phone ever renders.
//
// HostView asks for the recorded history (Phase 12). It is answered here with
// an empty one: a real request from this project would fail and draw the
// "No recorded history yet" note, which no page with a daemon behind it shows,
// and the measurement would be of a shape that does not exist.
beforeEach(async () => {
  vi.spyOn(api, 'hostHistory').mockResolvedValue(historySchema.parse({ series: {} }))
  await page.viewport(PHONE_WIDTH, 900)
})

afterEach(async () => {
  cleanup()
  vi.restoreAllMocks()
  forget()
  await page.viewport(1200, 900)
})

describe('/host at 390 px', () => {
  it('fits the amd64 desktop shape: notices, many sensors and fans, twelve virtual interfaces', () => {
    const phone = renderAtPhoneWidth(amd64())
    expect(phone.getBoundingClientRect().width).toBe(PHONE_WIDTH)
    // The shape is what it says it is: both notices, every sensor, every link.
    expect(phone.textContent).toContain('runs in a container')
    expect(phone.textContent).toContain('ProcSubset=all')
    expect(phone.textContent).toContain('AUXTIN0')
    expect(phone.textContent).toContain('fan5')
    expect(phone.textContent).toContain('wg0')
    // The virtual interfaces are laid out, not only present in the DOM: a
    // closed <details> would give them no box and nothing to measure.
    const lastVirtual = [...phone.querySelectorAll('li')].find((li) =>
      li.textContent?.startsWith('wg0'),
    )
    expect(lastVirtual?.getBoundingClientRect().height ?? 0).toBeGreaterThan(0)
    expect(overflowing(phone)).toEqual([])
  })

  it('wraps long identifiers instead of widening the page', () => {
    const host = longIdentifiers()
    const phone = renderAtPhoneWidth(host)
    expect(phone.getBoundingClientRect().width).toBe(PHONE_WIDTH)
    for (const s of [host.device.hostname, host.device.model, host.device.os, host.device.kernel]) {
      if (!s.readable) throw new Error('shape built with an unreadable identifier')
      expect(phone.textContent).toContain(s.value)
    }
    expect(phone.textContent).toContain(host.service.data_dir.path)
    expect(phone.textContent).toContain(host.live.filesystems[0]?.device)
    expect(overflowing(phone)).toEqual([])
  })
})
