import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { act, cleanup, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { Schematic } from '@/api'
// The stylesheet is imported for its effect, not its exports: every class under
// measurement here is generated by Tailwind from this entry point. Without it
// the elements below are unstyled and every measurement is a measurement of
// nothing that happens to pass.
import '@/index.css'
import { ImagesView } from './images'

/**
 * The layout suite. This is the first thing in this repository that opens the UI
 * in a real browser at all.
 *
 * It exists because jsdom performs no layout. The 108 tests in `images.test.tsx`
 * can read a class attribute and a text node; they cannot see a line box or a
 * rendered width, and during this phase's UAT that gap produced a real defect
 * reported as refuted — a test named `cannot split a repository name across a
 * line break` asserted the absence of two class names and passed while
 * `metal-installer-secureboot` was splitting after a hyphen so its first line
 * read `metal-installer` (02-UAT.md G-02-10).
 *
 * What this suite covers, and it is exactly two things:
 *
 *   1. The rendered width of the schematic detail dialog (02-UAT.md G-02-19).
 *   2. The line boxes of a reference's repository-name segment, for all four
 *      installer names, across a swept range of container widths (G-02-10).
 *
 * What it does NOT cover, said plainly so that nobody cites this file for a
 * claim it does not make: this is not a general browser suite and it is not an
 * end-to-end test. It renders React components against a faked `fetch`; no
 * binary runs, no bundle is served, and the embedded UI has still never been
 * driven end to end in a browser. That standing concern is untouched by this
 * file.
 */

vi.mock('@/routes/__root', () => ({
  authenticatedRoute: { addChildren: () => undefined },
}))

const SCHEMATIC_ID = 'a'.repeat(64)
const TALOS_VERSION = 'v1.13.9'

const RECORD: Schematic = {
  id: SCHEMATIC_ID,
  cluster: '',
  name: 'workers',
  talos_version: TALOS_VERSION,
  canonical: 'customization: {}\n',
  extensions: [],
  kernel_args: [],
  meta: [],
  usable: true,
  probed_at: '2026-08-29T10:00:00Z',
  probe_reason: '',
  arch: 'amd64',
  created_at: '2026-08-29T10:00:00Z',
  rev: 1,
}

/**
 * The smallest fetch stub that reaches an open detail dialog: the version list,
 * the extension catalog, the saved list, the record and its assets. It is
 * deliberately not a copy of `images.test.tsx`'s `stubFactory` — nothing here
 * asserts a request body, and a second full-fidelity fake would be a second
 * thing to keep in step for no gain.
 */
function stubFactory() {
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { 'Content-Type': 'application/json' },
    })

  vi.stubGlobal(
    'fetch',
    vi.fn(async (input: string) => {
      const url = new URL(String(input), 'https://127.0.0.1:8443')

      if (url.pathname === '/api/v1/factory/versions') {
        return json({
          stable: ['v1.12.0', 'v1.13.8', TALOS_VERSION],
          prerelease: [],
          newest_stable: TALOS_VERSION,
          broken: {},
        })
      }
      if (url.pathname === '/api/v1/factory/extensions') {
        return json({ version: url.searchParams.get('version') ?? '', extensions: [] })
      }
      if (url.pathname === '/api/v1/schematics') {
        return json([RECORD])
      }
      if (url.pathname === `/api/v1/schematics/${SCHEMATIC_ID}/assets`) {
        const version = url.searchParams.get('version') ?? TALOS_VERSION
        const arch = url.searchParams.get('arch') ?? 'amd64'
        return json({
          iso: `https://factory.talos.dev/image/${SCHEMATIC_ID}/${version}/metal-${arch}.iso`,
          pxe: `https://factory.talos.dev/pxe/${SCHEMATIC_ID}/${version}/metal-${arch}`,
          disk_image: `https://factory.talos.dev/image/${SCHEMATIC_ID}/${version}/metal-${arch}.raw.zst`,
          cmdline: `https://factory.talos.dev/image/${SCHEMATIC_ID}/${version}/cmdline-metal-${arch}`,
          installer: `factory.talos.dev/metal-installer/${SCHEMATIC_ID}:${version}`,
          warnings: [],
        })
      }
      if (url.pathname === `/api/v1/schematics/${SCHEMATIC_ID}`) {
        return json(RECORD)
      }
      return json({ type: 'about:blank', title: 'unrouted in this test' }, 500)
    }),
  )
}

function renderImages() {
  const client = new QueryClient({
    defaultOptions: { queries: { retry: false, gcTime: 0 }, mutations: { retry: false } },
  })
  return render(
    <QueryClientProvider client={client}>
      <ImagesView />
    </QueryClientProvider>,
  )
}

beforeEach(() => {
  // A real browser has matchMedia, ResizeObserver and pointer capture, so none
  // of `src/test/setup.ts`'s prostheses are installed here. `scrollTo` is
  // stubbed only because jsdom's absence of it is what the route's own code was
  // written against; the browser's implementation would scroll the harness page
  // during the run.
  vi.stubGlobal('scrollTo', vi.fn())
})

afterEach(() => {
  cleanup()
  vi.unstubAllGlobals()
  vi.restoreAllMocks()
})

/**
 * Waits for an element's entry animation to finish before it is measured.
 *
 * `getBoundingClientRect()` returns the *transformed* border box, and the dialog
 * opens with `data-open:zoom-in-95` — a 100ms scale from 0.95. Measuring the
 * instant it appears reports 745.34px for an element whose used width is 768px,
 * which looks exactly like a width bug and is not one. This is a real hazard for
 * every measurement in this file, so it is a named helper rather than a sleep.
 */
async function settled(element: Element): Promise<void> {
  // Inside `act` because finishing the animation is what lets Radix's Presence
  // commit its own state update; outside it, React warns on every measurement
  // and the warning is indistinguishable from a real one.
  await act(async () => {
    await Promise.all(element.getAnimations({ subtree: true }).map((each) => each.finished))
  })
}

describe('the schematic detail dialog, measured', () => {
  it('renders wider than the 384px the UAT measured', async () => {
    // G-02-19. Plan 02-15 moved the caller's width rule to `sm:max-w-3xl` so it
    // stops being outranked by `DialogContent`'s own `sm:max-w-sm`, and asserted
    // the merged class attribute in jsdom — the only half jsdom can check. This
    // is the other half.
    //
    // 384px is `max-w-sm` (24rem) and is the number this test exists to prove is
    // gone: the UAT measured exactly that at a 1200px viewport, with the wide
    // rule present on the element and doing nothing.
    //
    // The expectation is 768px — `--container-3xl` is 48rem at a 16px root — but
    // that figure is a token derivation, which is why the hard assertion is the
    // regression guard `> 384` and the exact value is checked separately. A
    // disagreement between the two is a finding about the tokens, not a test to
    // loosen.
    //
    // This test also guards the project itself. In an environment that performs
    // no layout every rect is zero, so `> 384` fails loudly if the browser
    // project is ever misconfigured back into jsdom.
    stubFactory()
    const user = userEvent.setup()

    renderImages()
    await user.click(await screen.findByRole('button', { name: `Schematic ${RECORD.name}` }))

    const dialog = await screen.findByRole('dialog')
    await settled(dialog)
    const width = dialog.getBoundingClientRect().width

    expect(width).toBeGreaterThan(384)
    // The derivation and the measurement agree. They were checked separately
    // before they were asserted together: a bare element carrying this exact
    // class set measures 768px at this viewport, so 768 is an observation here
    // and not a restatement of the token table.
    expect(width).toBe(768)
  })
})
