import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { act, cleanup, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { Schematic } from '@/api'
// The stylesheet is imported for its effect, not its exports: every class under
// measurement here is generated by Tailwind from this entry point. Without it
// the elements below are unstyled and every measurement is a measurement of
// nothing that happens to pass.
import '@/index.css'
import { ImagesView, ReferenceValue } from './images'

/**
 * The layout suite. This is the first thing in this repository that opens the UI
 * in a real browser at all.
 *
 * It exists because jsdom performs no layout. The jsdom project's 111 tests can
 * read a class attribute and a text node; they cannot see a line box or a
 * rendered width, and during this phase's UAT that gap produced a real defect
 * reported as refuted — a test named `cannot split a repository name across a
 * line break` asserted the absence of two class names and passed while
 * `metal-installer-secureboot` was splitting after a hyphen so its first line
 * read `metal-installer` (02-UAT.md G-02-10).
 *
 * What this suite covers, and it is exactly two things:
 *
 *   1. The rendered width of the schematic detail dialog (02-UAT.md G-02-19).
 *   2. The line boxes of a reference's repository-name segment, for all four
 *      installer names, across a swept range of container widths (G-02-10).
 *
 * What it does NOT cover, said plainly so that nobody cites this file for a
 * claim it does not make: this is not a general browser suite and it is not an
 * end-to-end test. It renders React components against a faked `fetch`; no
 * binary runs, no bundle is served, and the embedded UI has still never been
 * driven end to end in a browser. That standing concern is untouched by this
 * file.
 */

vi.mock('@/routes/__root', () => ({
  authenticatedRoute: { addChildren: () => undefined },
}))

const SCHEMATIC_ID = 'a'.repeat(64)
const TALOS_VERSION = 'v1.13.9'

const RECORD: Schematic = {
  id: SCHEMATIC_ID,
  cluster: '',
  name: 'workers',
  talos_version: TALOS_VERSION,
  canonical: 'customization: {}\n',
  extensions: [],
  kernel_args: [],
  meta: [],
  usable: true,
  probed_at: '2026-08-29T10:00:00Z',
  probe_reason: '',
  arch: 'amd64',
  created_at: '2026-08-29T10:00:00Z',
  rev: 1,
}

/**
 * The smallest fetch stub that reaches an open detail dialog: the version list,
 * the extension catalog, the saved list, the record and its assets. It is
 * deliberately not a copy of `images.test.tsx`'s `stubFactory` — nothing here
 * asserts a request body, and a second full-fidelity fake would be a second
 * thing to keep in step for no gain.
 */
function stubFactory() {
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { 'Content-Type': 'application/json' },
    })

  vi.stubGlobal(
    'fetch',
    vi.fn(async (input: string) => {
      const url = new URL(String(input), 'https://127.0.0.1:8443')

      if (url.pathname === '/api/v1/factory/versions') {
        return json({
          stable: ['v1.12.0', 'v1.13.8', TALOS_VERSION],
          prerelease: [],
          newest_stable: TALOS_VERSION,
          broken: {},
        })
      }
      if (url.pathname === '/api/v1/factory/extensions') {
        return json({ version: url.searchParams.get('version') ?? '', extensions: [] })
      }
      if (url.pathname === '/api/v1/schematics') {
        return json([RECORD])
      }
      if (url.pathname === `/api/v1/schematics/${SCHEMATIC_ID}/assets`) {
        const version = url.searchParams.get('version') ?? TALOS_VERSION
        const arch = url.searchParams.get('arch') ?? 'amd64'
        return json({
          iso: `https://factory.talos.dev/image/${SCHEMATIC_ID}/${version}/metal-${arch}.iso`,
          pxe: `https://factory.talos.dev/pxe/${SCHEMATIC_ID}/${version}/metal-${arch}`,
          disk_image: `https://factory.talos.dev/image/${SCHEMATIC_ID}/${version}/metal-${arch}.raw.zst`,
          cmdline: `https://factory.talos.dev/image/${SCHEMATIC_ID}/${version}/cmdline-metal-${arch}`,
          installer: `factory.talos.dev/metal-installer/${SCHEMATIC_ID}:${version}`,
          warnings: [],
        })
      }
      if (url.pathname === `/api/v1/schematics/${SCHEMATIC_ID}`) {
        return json(RECORD)
      }
      return json({ type: 'about:blank', title: 'unrouted in this test' }, 500)
    }),
  )
}

function renderImages() {
  const client = new QueryClient({
    defaultOptions: { queries: { retry: false, gcTime: 0 }, mutations: { retry: false } },
  })
  return render(
    <QueryClientProvider client={client}>
      <ImagesView />
    </QueryClientProvider>,
  )
}

beforeEach(() => {
  // A real browser has matchMedia, ResizeObserver and pointer capture, so none
  // of `src/test/setup.ts`'s prostheses are installed here. `scrollTo` is
  // stubbed only because jsdom's absence of it is what the route's own code was
  // written against; the browser's implementation would scroll the harness page
  // during the run.
  vi.stubGlobal('scrollTo', vi.fn())
})

afterEach(() => {
  cleanup()
  vi.unstubAllGlobals()
  vi.restoreAllMocks()
})

/**
 * Waits for an element's entry animation to finish before it is measured.
 *
 * `getBoundingClientRect()` returns the *transformed* border box, and the dialog
 * opens with `data-open:zoom-in-95` — a 100ms scale from 0.95. Measuring the
 * instant it appears reports 745.34px for an element whose used width is 768px,
 * which looks exactly like a width bug and is not one. This is a real hazard for
 * every measurement in this file, so it is a named helper rather than a sleep.
 */
async function settled(element: Element): Promise<void> {
  // Inside `act` because finishing the animation is what lets Radix's Presence
  // commit its own state update; outside it, React warns on every measurement
  // and the warning is indistinguishable from a real one.
  await act(async () => {
    await Promise.all(element.getAnimations({ subtree: true }).map((each) => each.finished))
  })
}

describe('the schematic detail dialog, measured', () => {
  it('renders wider than the 384px the UAT measured', async () => {
    // G-02-19. Plan 02-15 moved the caller's width rule to `sm:max-w-3xl` so it
    // stops being outranked by `DialogContent`'s own `sm:max-w-sm`, and asserted
    // the merged class attribute in jsdom — the only half jsdom can check. This
    // is the other half.
    //
    // 384px is `max-w-sm` (24rem) and is the number this test exists to prove is
    // gone: the UAT measured exactly that at a 1200px viewport, with the wide
    // rule present on the element and doing nothing.
    //
    // The expectation is 768px — `--container-3xl` is 48rem at a 16px root — but
    // that figure is a token derivation, which is why the hard assertion is the
    // regression guard `> 384` and the exact value is checked separately. A
    // disagreement between the two is a finding about the tokens, not a test to
    // loosen.
    //
    // This test also guards the project itself. In an environment that performs
    // no layout every rect is zero, so `> 384` fails loudly if the browser
    // project is ever misconfigured back into jsdom.
    stubFactory()
    const user = userEvent.setup()

    renderImages()
    await user.click(await screen.findByRole('button', { name: `Schematic ${RECORD.name}` }))

    const dialog = await screen.findByRole('dialog')
    await settled(dialog)
    const width = dialog.getBoundingClientRect().width

    expect(width).toBeGreaterThan(384)
    // The derivation and the measurement agree. They were checked separately
    // before they were asserted together: a bare element carrying this exact
    // class set measures 768px at this viewport, so 768 is an observation here
    // and not a restatement of the token table.
    expect(width).toBe(768)
  })
})

/*
 * ─── The repository name occupies one line box ────────────────────────────────
 *
 * 02-UAT.md G-02-10. `ReferenceValue` offers breaks at path separators with
 * `<wbr />` and refuses the rest with `break-normal`, and the doc comment argued
 * that this stops `metal-installer` wrapping into something a reader takes for
 * `installer`. It does not. UAX #14 gives a break opportunity after U+002D
 * HYPHEN-MINUS — line-break class HY — independently of `overflow-wrap` and
 * `word-break`, and neither `normal` value removes it.
 *
 * The test that was supposed to catch this asserted that the class string lacked
 * two utilities and that the text content was intact. Both remained true while
 * the name split, so it passed. This is the replacement, and it measures.
 */

/**
 * The four repository names that may carry an installer.
 *
 * Derived, not typed out: `installerCandidates` in
 * `internal/imagefactory/installer.go` builds the platform-prefixed name and the
 * legacy name, each carrying the SecureBoot suffix when the request asks for it.
 * Enumerating the four by hand is precisely how three of them went unexamined
 * when this property was first checked — only `metal-installer` was ever looked
 * at, and `metal-installer-secureboot` is the one that splits at the default
 * viewport.
 *
 * Exported because nothing in TypeScript can pin this to the Go list that is its
 * authority. A fifth candidate added to `installerCandidates` would leave this
 * sweep measuring four stale strings and still passing — a smaller instance of
 * exactly the defect this file exists to close. Plan 02-20 owns
 * `guard_drift_test.go` in `package imagefactory` and pins the two together
 * there, in wave 5; until it lands, this comment is the whole of the link.
 *
 * `INSTALLER_REPOSITORY_NAMES_LITERAL` below is what that Go test reads —
 * `strings.Contains` over this source, the way `TestWarningDetailsMatchTheUI`
 * reads `SchematicWarnings.tsx` — and the derivation above is what stops the
 * literals being an unchecked transcription. `agrees with the derivation` holds
 * the two together from this side.
 */
const INSTALLER_PLATFORM = 'metal'
const LEGACY_INSTALLER_REPO = 'installer'
const SECUREBOOT_REPO_SUFFIX = '-secureboot'

// biome-ignore lint/suspicious/noExportsInTest: plan 02-20's guard_drift_test.go binds this array to installerCandidates -- the export is that seam.
export const INSTALLER_REPOSITORY_NAMES: readonly string[] = [false, true].flatMap((secureBoot) => {
  const suffix = secureBoot ? SECUREBOOT_REPO_SUFFIX : ''
  return [
    `${INSTALLER_PLATFORM}-${LEGACY_INSTALLER_REPO}${suffix}`,
    `${LEGACY_INSTALLER_REPO}${suffix}`,
  ]
})

/** The same four names as literals, for a Go test to read out of this source. */
// biome-ignore lint/suspicious/noExportsInTest: read as source text by Go, not imported.
export const INSTALLER_REPOSITORY_NAMES_LITERAL: readonly string[] = [
  'metal-installer',
  'installer',
  'metal-installer-secureboot',
  'installer-secureboot',
]

/**
 * The swept range, in single-pixel steps.
 *
 * The audit measured the name splitting at column widths 40-115px and again at
 * 174-238px, with a safe gap between them — break windows are NOT monotonic in
 * width. That is why this sweeps rather than samples: the 400px viewport the
 * property was originally checked at produced a 152-168px column, sitting in
 * that gap, so "narrow until it looks cramped" passes through a safe window and
 * can never establish this.
 */
const SWEEP_FROM = 30
const SWEEP_TO = 280

/** A realistic reference: host, repository name, 64-hex schematic id, version. */
function referenceFor(repository: string): string {
  return `factory.talos.dev/${repository}/${'a'.repeat(64)}:${TALOS_VERSION}`
}

/** The text node holding exactly `text`, searched depth-first. */
function textNodeFor(root: Node, text: string): Text {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
  let node = walker.nextNode()
  while (node !== null) {
    if ((node as Text).data === text) {
      return node as Text
    }
    node = walker.nextNode()
  }
  throw new Error(`no text node holds ${JSON.stringify(text)}`)
}

/** Rounded so that sub-pixel noise cannot read as a second line. */
function lineTop(rect: DOMRect): number {
  return Math.round(rect.top * 100) / 100
}

/**
 * How many line boxes a text node occupies.
 *
 * A `Range` over the node yields one rect per line box it is laid out on, so
 * counting distinct `top` values counts lines. This is the measurement the class
 * assertions could not make: it is a fact about layout, and it exists only in an
 * engine that performs layout.
 */
function lineBoxCount(node: Text): number {
  const range = document.createRange()
  range.selectNodeContents(node)
  const tops = new Set<number>()
  for (const rect of Array.from(range.getClientRects())) {
    if (rect.width === 0 && rect.height === 0) {
      continue
    }
    tops.add(lineTop(rect))
  }
  return tops.size
}

/**
 * What each line actually reads, for the failure message.
 *
 * Character by character, so it is only ever run on the failure path. Knowing
 * *where* a name splits is the entire finding — `metal-installer-secureboot`
 * breaking after the first hyphen puts `metal-installer` on a line of its own,
 * and that first line is a different image's name.
 */
function lineContents(node: Text): string[] {
  const range = document.createRange()
  const lines = new Map<number, string>()
  for (let index = 0; index < node.data.length; index += 1) {
    range.setStart(node, index)
    range.setEnd(node, index + 1)
    const rect = range.getClientRects()[0]
    if (rect === undefined) {
      continue
    }
    const key = lineTop(rect)
    lines.set(key, (lines.get(key) ?? '') + node.data.charAt(index))
  }
  return [...lines.entries()].sort(([a], [b]) => a - b).map(([, text]) => text)
}

/**
 * One reference in a column whose width the test drives.
 *
 * A grid with a single explicit column, because that is what the reference sits
 * in for real: `AssetRow` is a `grid-cols-[minmax(0,8rem)_1fr_auto]` and the
 * value is a grid item. That matters — `overflow-x-auto` and `min-w-0` only do
 * anything to a grid item, and they are what let the 64-character id overflow
 * into a horizontal scroll instead of forcing the column wide.
 */
function mountReference(repository: string) {
  const value = referenceFor(repository)
  const { container } = render(
    <div data-column style={{ display: 'grid', gridTemplateColumns: `${SWEEP_FROM}px` }}>
      <ReferenceValue value={value} />
    </div>,
  )
  const column = container.querySelector<HTMLElement>('[data-column]')
  const reference = container.querySelector<HTMLElement>('[data-reference]')
  if (column === null || reference === null) {
    throw new Error('the reference did not mount')
  }
  return { column, reference, value }
}

describe('a repository name in an asset reference', () => {
  // The names are derived from the same construction the resolver uses, so this
  // is the check that the derivation still produces what everyone thinks it
  // does -- and it is what keeps the literals below honest, since those are the
  // form plan 02-20's Go guard reads out of this file.
  it('agrees with the derivation about which four names there are', () => {
    expect([...INSTALLER_REPOSITORY_NAMES]).toEqual([...INSTALLER_REPOSITORY_NAMES_LITERAL])
    expect(INSTALLER_REPOSITORY_NAMES).toHaveLength(4)
  })

  for (const repository of INSTALLER_REPOSITORY_NAMES) {
    it(`occupies one line box at every width from ${SWEEP_FROM}px to ${SWEEP_TO}px: ${repository}`, () => {
      const { column, reference, value } = mountReference(repository)

      // Mounted once and re-measured, not remounted per step. 251 remounts per
      // name is slow enough that the next person narrows the range, and a
      // narrowed range is how this property went unmeasured in the first place.
      const split: { width: number; lines: string[] }[] = []

      for (let width = SWEEP_FROM; width <= SWEEP_TO; width += 1) {
        column.style.gridTemplateColumns = `${width}px`

        // The fix must not change one character of the reference. The Copy
        // control writes this value and an operator who drags a selection over
        // it gets the rendered text, so a mitigation that swapped the hyphen for
        // a look-alike would satisfy the line-box assertion and hand out an
        // invalid OCI reference. Asserted at every width, not once.
        expect(reference.textContent).toBe(value)

        const name = textNodeFor(reference, repository)
        if (lineBoxCount(name) !== 1) {
          split.push({ width, lines: lineContents(name) })
        }
      }

      expect(
        split.map((each) => `${each.width}px: ${each.lines.join(' ⏎ ')}`).join('\n'),
        `${repository} split across a line break at ${split.length} of the swept widths`,
      ).toBe('')
    })
  }

  it('still offers a break between path segments', () => {
    // The narrow guarantee is about what is INSIDE a segment. Breaking between
    // segments is wanted and is what `<wbr />` is there for, so this is here to
    // stop the fix being over-tightened into `nowrap` on the whole reference.
    const { column, reference } = mountReference('metal-installer')
    column.style.gridTemplateColumns = '120px'

    const host = textNodeFor(reference, 'factory.talos.dev')
    const name = textNodeFor(reference, 'metal-installer')

    const hostRange = document.createRange()
    hostRange.selectNodeContents(host)
    const nameRange = document.createRange()
    nameRange.selectNodeContents(name)

    const hostRect = hostRange.getClientRects()[0]
    const nameRect = nameRange.getClientRects()[0]
    if (hostRect === undefined || nameRect === undefined) {
      throw new Error('the reference measured as nothing')
    }
    expect(lineTop(nameRect)).toBeGreaterThan(lineTop(hostRect))
  })
})
