import { render, screen } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import type { Release } from '@/api'
// Imported for its effect: every class measured below is generated by Tailwind
// from this entry point, and without it the panel is unstyled and the
// measurements measure nothing.
import '@/index.css'
import { ReleaseNotes } from './WhatsNew'

/**
 * The release-notes panel has to contain its own list.
 *
 * This is here rather than in the jsdom suite because jsdom performs no layout,
 * and the defect it guards is invisible without it. DialogContent lays its
 * children out in a grid whose rows take an automatic minimum size from their
 * content, so `max-h-[85vh]` clipped the panel while the list carried on
 * rendering underneath it, off the bottom of the box: the last release in the
 * changelog was on screen in the DOM and unreachable by eye or by scrollbar.
 *
 * Every jsdom test passed against that. They asserted the text was rendered,
 * and it was.
 */

function release(version: string, date: string, count: number): Release {
  return {
    version,
    series: 'v1.16',
    date,
    changes: Array.from({ length: count }, (_, i) => ({
      icon: '•',
      // Long enough to wrap several times, because the failure is a function of
      // rendered height and a one-line entry would not reach it.
      text:
        `Entry ${i} of ${version}. ` +
        'It is deliberately long so that the list is taller than any dialog ' +
        'could be, which is the only condition under which the overflow is ' +
        'visible at all, and a short fixture would pass against the defect.',
    })),
  }
}

// Far more than a viewport can hold, which is the point.
const RELEASES: Release[] = [
  release('v1.16.0', '2026-09-15', 6),
  release('v1.16.0-beta.2', '2026-09-15', 6),
  release('v1.16.0-beta.1', '2026-09-14', 9),
]

describe('the release notes panel, laid out', () => {
  it('keeps its list inside the dialog instead of rendering past the bottom', async () => {
    render(
      <ReleaseNotes open onOpenChange={() => undefined} version="v1.16.0" releases={RELEASES} />,
    )

    const dialog = await screen.findByRole('dialog')
    const box = dialog.getBoundingClientRect()

    // The dialog itself fits the viewport. max-h-[85vh] says so; this is the
    // assertion that the constraint is actually being applied.
    expect(box.top).toBeGreaterThanOrEqual(0)
    expect(box.bottom).toBeLessThanOrEqual(window.innerHeight + 1)

    // The list is taller than the space it has — otherwise this test proves
    // nothing, because a list that fits cannot overflow.
    const scroller = dialog.querySelector('div.overflow-y-auto')
    if (scroller === null) {
      throw new Error('no scroll container in the panel')
    }
    expect(scroller.scrollHeight).toBeGreaterThan(scroller.clientHeight)

    // And every entry is inside the dialog rather than below it. The last one
    // is the one that was unreachable, so it is the one measured; it is found
    // by text rather than by position so that reordering the fixture cannot
    // quietly make this assertion about a different element.
    const last = screen.getByText(/Entry 8 of v1\.16\.0-beta\.1/)
    scroller.scrollTop = scroller.scrollHeight
    await new Promise((resolve) => requestAnimationFrame(resolve))

    const lastBox = last.getBoundingClientRect()
    expect(lastBox.bottom).toBeLessThanOrEqual(box.bottom + 1)
  })
})
